apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: odujsllzd-java-springboot
  janus-idp.io/tekton: odujsllzd-java-springboot
  backstage.io/kubernetes-id: odujsllzd-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: odujsllzd-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
